[x] Iniciar
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Set.html
[x] toString()
[x] contains()
[x] toString()
[x] Collections.min()
[x] Collections.max()
[x] iterator()
[x] iterator().hasNext()
[x] iterator().next()
[x] size()
[x] remove()
[x] iterator().remove()
[x] new LinkedHashMap()
[x] new TreeMap()
[x] clear()
[x] isEmpty()